---
title: "ESM 244 Week 2 Lab"
author: "Anna Talken"
date: "1/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(palmerpenguins)
library(here)

## For PCA
library(ggfortify)

# For ggplot customization
library(readxl)
library(gghighlight)
library(lubridate)
library(plotly)

# To make compound figures
library(patchwork)
```

## Part 1: PCA with penguins

```{r}
penguin_pca <- penguins %>% 
  select(body_mass_g, ends_with("_mm"))  %>% #shortcut to select columns that end with _mm
  drop_na() %>% 
  scale() %>%  #scale variables 
  prcomp()

penguin_pca$rotation #loadings for different variables in PCA

penguin_complete <- penguins %>% 
  drop_na(body_mass_g, ends_with("_mm"))

#Create a biplot
autoplot(penguin_pca,
         data = penguin_complete,
         colour = 'species',
         loadings = TRUE,
         loadings.label = TRUE) + #shows locations on PC1 and PC2 of all observations in data (axis rotation) 
  theme_minimal()
# almost 69% of variance explained in PC1, and 19% explained in PC2, can also see that Adelie and Chinstrap overlap in multivariance
```

### Part 2: ggplot2 customization and reading in different file types

#### Read in an .xlsx file and do some wrangling

```{r}
fish_noaa <- read_excel(here("data", "foss_landings.xlsx")) %>% 
  clean_names() %>% 
  mutate(across(where(is.character), tolower)) %>%  #transforming columns that have character class to lowercase
  mutate(nmfs_name = str_sub(nmfs_name, end = -4)) %>%  #removing the last 4 characters of the NMFS name column
  filter(confidentiality == "public")
```

Make a customized graph:

```{r}
fish_plot <- ggplot(data = fish_noaa, aes(x = year, y = pounds)) +
  geom_line(aes(color = nmfs_name), show.legend = FALSE) +
  theme_minimal()

fish_plot

ggplotly(fish_plot) #makes interactive graph

### Use gghighlight to highlight certain series
ggplot(data = fish_noaa, aes(x = year, y = pounds, group = nmfs_name)) +
  geom_line(aes(color = nmfs_name)) +
  theme_minimal() +
  gghighlight(max(pounds) > 1e8) # highlights designated variable, only applies color scheme to this series too

```

#### Read in data from a URL, 'lubridate()', 'mutate()', make a graph with months in logical order

```{r}
monroe_wt <- read_csv("https://data.bloomington.in.gov/dataset/2c81cfe3-62c2-46ed-8fcf-83c1880301d1/resource/13c8f7aa-af51-4008-80a9-56415c7c931e/download/mwtpdailyelectricitybclear.csv")
```

```{r}
monroe_ts <- monroe_wt %>% 
  mutate(date = mdy(date)) %>% 
  mutate(record_month = month(date)) %>% 
  mutate(month_name = month.abb[record_month]) %>%  #replacing the number of the month with the abbreviated name of the month
  mutate(month_name = fct_reorder(month_name, record_month))

ggplot(data = monroe_ts, aes(month_name, y = total_kWh)) +
  geom_jitter()
```

### Part 3: Compound figures with 'patchwork'

```{r}
graph_a <- ggplot(data = penguins, aes(x = body_mass_g, y = flipper_length_mm)) +
  geom_point()

graph_b <- ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(aes(color = species), show.legend = FALSE)

graph_a

# Use | to put graphs side by side
# Use / to put graphs one over the other

(graph_a|graph_b) / fish_plot

graph_c <- (graph_a | graph_b) / fish_plot & theme_dark()

graph_c

ggsave(here("fig", "graph_c_at.png"), width = 5, height = 6) # save graph to a file !
```



















